### ISSUE TITLE
Plugin doesnt work.

### ISSUE THREAD

**Issue by NyleCohen** [PureDark/BSDarthMaul#3]
When I installed the plugin and ran beat saber the plugin configuration did not appear. How can I get this working??

**Comment by NewSaber** [comment]
This mod currently doesn't work with the latest beat saber version, we'll just have to wait for it to be updated.

**Comment by NyleCohen** [comment]
Ok, thank you!

**Comment by PureDark** [comment]
Get v0.5.0 from releases.
